include: package:lints/recommended.yaml

analyzer:
  exclude: [build/**, "**/*.g.dart"]
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    unnecessary_breaks: true
    unawaited_futures: true
    prefer_single_quotes: true